language: java
jdk:
  - oraclejdk8
sudo: false
services:
  - mysql
before_install:
  - mysql -u root --password="" < CryptoFolio/src/test/ressources/travis.sql
script: mvn -f CryptoFolio/ clean verify
